const GUNS = {
  1: {
    id: 1,
    name: "Pistol",
    type: "semi",
    damage: 25,
    rpm: 180,
    bulletSpeed: 900,
    magazine: 12,
    reloadTime: 1.2,
    spreadDeg: 2,
    range: 1200,
    pellets: 1,
    reserveClips: Infinity,
    heavy: false,
    projectile: false,
    infiniteAmmo: true,
    trailColor: "#ffffff"
  },
  2: {
    id: 2,
    name: "Assault Rifle",
    type: "auto",
    damage: 18,
    rpm: 600,
    bulletSpeed: 1100,
    magazine: 30,
    reloadTime: 1.8,
    spreadDeg: 4,
    range: 1600,
    pellets: 1,
    reserveClips: 4,
    heavy: false,
    projectile: false,
    infiniteAmmo: false,
    trailColor: "#00ff88"
  },
  3: {
    id: 3,
    name: "Shotgun",
    type: "semi",
    damage: 15,
    rpm: 75,
    bulletSpeed: 700,
    magazine: 6,
    reloadTime: 2.2,
    spreadDeg: 18,
    range: 400,
    pellets: 6,
    reserveClips: 4,
    heavy: false,
    projectile: false,
    infiniteAmmo: false,
    trailColor: "#ffb800"
  },
  4: {
    id: 4,
    name: "Sniper Rifle",
    type: "semi",
    damage: 95,
    rpm: 45,
    bulletSpeed: 2500,
    magazine: 5,
    reloadTime: 2.8,
    spreadDeg: 0.2,
    range: 3200,
    pellets: 1,
    reserveClips: 4,
    heavy: false,
    projectile: false,
    infiniteAmmo: false,
    trailColor: "#7dd3fc"
  },
  5: {
    id: 5,
    name: "SMG",
    type: "auto",
    damage: 12,
    rpm: 900,
    bulletSpeed: 950,
    magazine: 40,
    reloadTime: 1.4,
    spreadDeg: 6,
    range: 900,
    pellets: 1,
    reserveClips: 4,
    heavy: false,
    projectile: false,
    infiniteAmmo: false,
    trailColor: "#10b981"
  },
  6: {
    id: 6,
    name: "LMG",
    type: "auto",
    damage: 20,
    rpm: 450,
    bulletSpeed: 1000,
    magazine: 100,
    reloadTime: 4,
    spreadDeg: 8,
    range: 1400,
    pellets: 1,
    reserveClips: 3,
    heavy: true,
    projectile: false,
    infiniteAmmo: false,
    trailColor: "#f59e0b"
  },
  7: {
    id: 7,
    name: "Rocket Launcher",
    type: "semi",
    damage: 120,
    rpm: 30,
    bulletSpeed: 500,
    magazine: 3,
    reloadTime: 3.5,
    spreadDeg: 1,
    range: 1800,
    pellets: 1,
    reserveClips: 3,
    heavy: true,
    projectile: true,
    splashRadius: 120,
    infiniteAmmo: false,
    trailColor: "#fb7185"
  },
  8: {
    id: 8,
    name: "Grenade Launcher",
    type: "semi",
    damage: 70,
    rpm: 60,
    bulletSpeed: 600,
    magazine: 6,
    reloadTime: 2.5,
    spreadDeg: 3,
    range: 1000,
    pellets: 1,
    reserveClips: 3,
    heavy: false,
    projectile: true,
    splashRadius: 100,
    maxBounces: 1,
    infiniteAmmo: false,
    trailColor: "#c084fc"
  }
};

const GUN_LIST = Object.values(GUNS);

function getGunConfig(gunId) {
  return GUNS[gunId] || GUNS[1];
}

module.exports = {
  GUNS,
  GUN_LIST,
  getGunConfig
};
